workflows:
  android-build:
    name: Android LSPosed Hook Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_VERSION: 17
        GRADLE_VERSION: 7.5
    scripts:
      - name: Set up Java
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v $JAVA_VERSION)
      - name: Extract project files
        script: |
          unzip -o LSPosedHookModule_Fixed.zip -d .
      - name: Install Gradle manually
        script: |
          curl -sS https://downloads.gradle-dn.com/distributions/gradle-$GRADLE_VERSION-bin.zip -o gradle.zip
          unzip -q gradle.zip
          export PATH=$PWD/gradle-$GRADLE_VERSION/bin:$PATH
      - name: Build debug APK
        script: |
          cd LSPosedHookModule
          gradle assembleDebug
    artifacts:
      - LSPosedHookModule/app/build/outputs/apk/debug/app-debug.apk
