name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Force Checkout Repository (Fix Exit Code 128)
        run: |
          rm -rf .git
          git init
          git remote add origin https://github.com/Royal378/11.git
          git fetch --depth=1 origin main
          git reset --hard origin/main
      
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d android-sdk
          export ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-31" "build-tools;31.0.0" "platform-tools"

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: app/build/outputs/apk/debug/app-debug.apk
